// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Infrastructure;

#nullable disable

namespace Warehouse.Infrastructure.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    partial class WarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.InventoryAggregate.InventoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CargoOwner")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OpenCount")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.Property<long>("StorehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("StorehouseId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("StorehouseId"));

                    b.HasIndex("StorehouseId", "CargoOwner", "SKU", "LocationCode")
                        .IsUnique();

                    b.ToTable("InventoryRecord");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StockInAggregate.StockInDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CargoOwner")
                        .HasColumnType("bigint");

                    b.Property<int>("ClaimCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FactCount")
                        .HasColumnType("int");

                    b.Property<string>("PaperSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("StockInPaperId")
                        .HasColumnType("bigint");

                    b.Property<int>("StorehouseShelfedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CargoOwner");

                    b.HasIndex("PaperSerialNumber");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("PaperSerialNumber"));

                    b.HasIndex("SKU");

                    b.HasIndex("StockInPaperId");

                    b.ToTable("StockInDetail");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StockInAggregate.StockInPaper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CargoOwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaperSerialNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StockhouseId")
                        .HasColumnType("bigint");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("PaperSerialNumber");

                    b.HasIndex("TenantId", "StockhouseId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("TenantId", "StockhouseId"));

                    b.ToTable("StockInPaper");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StorehouseAggregate.StockLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("AllowOverload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("MaxVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<long>("StorehouseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Useable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<float>("UsedVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("StorehouseId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("StorehouseId"));

                    b.HasIndex("LocationCode", "StorehouseId")
                        .IsUnique();

                    b.ToTable("StockLocation");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StorehouseAggregate.Storehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("Storehouses");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StockInAggregate.StockInDetail", b =>
                {
                    b.HasOne("Warehouse.Domain.AggregatesModel.StockInAggregate.StockInPaper", null)
                        .WithMany("StockInDetails")
                        .HasForeignKey("StockInPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StorehouseAggregate.StockLocation", b =>
                {
                    b.HasOne("Warehouse.Domain.AggregatesModel.StorehouseAggregate.Storehouse", null)
                        .WithMany("StockLocations")
                        .HasForeignKey("StorehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StorehouseAggregate.Storehouse", b =>
                {
                    b.OwnsOne("Warehouse.Domain.AggregatesModel.StorehouseAggregate.Address", "WarehouseAddress", b1 =>
                        {
                            b1.Property<long>("StorehouseId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DetailAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StorehouseId");

                            b1.ToTable("Storehouses");

                            b1.WithOwner()
                                .HasForeignKey("StorehouseId");
                        });

                    b.Navigation("WarehouseAddress");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StockInAggregate.StockInPaper", b =>
                {
                    b.Navigation("StockInDetails");
                });

            modelBuilder.Entity("Warehouse.Domain.AggregatesModel.StorehouseAggregate.Storehouse", b =>
                {
                    b.Navigation("StockLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
